<template>
  <div class="wrapper">
    <div class="content">
      <h1>Mi Account User Agreement</h1>
      <p>Welcome to Mi Account!</p>
      <p>This user agreement between you and Xiaomi Inc. and its affiliates (hereinafter referred to as "Xiaomi", "we", "our", or "us") governs your creation and use of a Mi Account. <strong>Please carefully read and fully understand all the terms and conditions of this user agreement (hereinafter referred to as "this Agreement"), especially those regarding service fees, applicable laws, dispute resolution, the exemption of Xiaomi from liabilities or restrictions to its liabilities, and your rights and obligations. Those terms and conditions are highlighted in bold for your convenience. If you have not reached the age of majority or for any other reason do not possess full capacity for civil conduct, you should read and decide whether to agree to this Agreement accompanied by a guardian.</strong></p>
      <p><strong>Creating an account and using our services both constitute your agreement to accept and be bound by the terms and conditions of this Agreement.</strong></p>
      <h2>1. Introduction to Mi Account</h2>
      <p>1.1 Xiaomi authorizes you, through this Agreement, to create, sign in to, and use Mi Account and its related services. All Mi Accounts are the property of Xiaomi, and you have the right to use your Mi Account as the original registrant of the account.</p>
      <p>1.2. A Mi Account gives you access to products and services provided by Xiaomi. Examples include Xiaomi Cloud, Themes, GetApps, IoT platform, Mi.com and Youpinlab.com. With a Mi Account, you can get Mi Coins and make in-app purchases, such as virtual goods in a game, ebooks, and more. You agree that when you use any specific service, you accept and will be bound by the terms and conditions of both this Agreement and the relevant service agreements of the specific service.</p>
      <h2>2. Creating and using an account</h2>
      <h3>2.1 Creating an account</h3>
      <p>2.1.1 You confirm that you possess full capacity for civil conduct as defined by the laws and regulations of the People's Republic of China before beginning the registration process for Xiaomi services. If you do not possess full capacity for your actions, you and your guardian shall bear all the consequences arising therefrom in accordance with the law.</p>
      <p>2.1.2 You can create a Mi Account by signing up. Go to the Mi Account sign-up page, read and agree to the Mi Account User Agreement, and follow the on-screen prompts. <strong>You agree to provide true, accurate, and complete information about yourself when you sign up, including but not limited to your phone number and email address. Xiaomi is not liable for any problems caused by false or mistaken registration information or failure to update user information. </strong>You can find and update your account details in your account settings. <strong>You should register your account using your real identity. </strong>You will not be able to sign up for a Mi Account if you include illegal or inappropriate content in your profile, including your nickname and profile photo. If you include any false, illegal, or inappropriate content in your profile, <strong>Xiaomi may correct the information within a limited timeframe, or suspend or terminate your account without prior notice. </strong>After you fill in the information as prompted on the registration page, read and agree to the terms of this Agreement, and complete all the registration procedures, you may obtain a Mi Account and become a Mi user.</p>
      <h3>2.2 Using your account</h3>
      <p><strong>2.2.1 You are responsible for all activity that happens on or through your account and the consequences thereof, including but not limited to acceptance of service-specific terms, sharing and disclosure of information, and the purchase of products and services.</strong></p>
      <p>2.2.2 Your Mi Account is for your use only. Your account information includes both your personal details as well as Xiaomi business information. You may not directly or indirectly allow third parties to use your Mi Account or access information on your account without Xiaomi's consent. Xiaomi reserves the right to terminate this Agreement or suspend access to our services if we reasonably believe, after examination following policy violation procedures and standards, that your account security is in danger, or that Xiaomi's information security may be compromised by the use of your account.</p>
      <p>2.2.3 When you use a third-party account to sign in to Xiaomi services, your third-party account is linked with your Mi Account. We will use your information shared by third parties with your consent, such as the profile photo of the linked third-party account. This Agreement applies to any and all usage of your Mi Account.</p>
      <h3>2.3 Accounts, passwords, and security</h3>
      <p>2.3.1 A Mi Account includes an account name and password. An account name can be a Mi Account ID or phone number. You are entirely responsible for maintaining the confidentiality of the information you hold for your account and updating your password regularly. <strong>If you lose or forget your account information, you can recover it by following our account recovery steps. You'll be asked to provide the required information to verify the account is yours. We won't be able to process your request if the info you provided is inaccurate, invalid, or incomplete.</strong></p>
      <p>2.3.2 If you're using an account that was not created via Xiaomi or by you, but you know the password of the account, contact us or the account creator immediately and stop using or signing into that account.</p>
      <h3>2.4 Transfer of the account</h3>
      <p>2.4.1 You may use your Mi Account within the scope described in this Agreement. You shall not create a Mi Account for malicious purposes. You shall not gift, borrow, rent, transfer, sell, give away for free, or use any other method to grant access to your Mi Account to other people. Xiaomi has the right to independently evaluate and respond to the above behaviors. You shall bear any responsibilities arising therefrom, <strong>and Xiaomi reserves the right to pursue legal action against the people involved in the aforementioned behaviors. All the liability arising therefrom shall be borne by you.</strong></p>
      <p><strong>2.4.2 Xiaomi has the right to take the following steps in accordance with this Agreement and relevant laws and regulations:</strong></p>
      <p><strong>2.4.2.1 If you violate laws and regulations, Xiaomi's individual terms, or business principles, Xiaomi has the right to make independent judgments and undertake time-limited corrections, or suspend or terminate your Mi Account at any time, and decide whether to resume use according to the situation.</strong></p>
      <p><strong>2.4.2.2 If Xiaomi finds that you are not the original registrant of the Mi Account, Xiaomi reserves the right to terminate your use of the account without notice.</strong></p>
      <p><strong>2.4.2.3 Xiaomi reserves the right to correct, suspend, or terminate your Mi Account within a limited time period in accordance with this Agreement or relevant laws, and any resultant losses to you (including but not limited to communication interruptions, loss of user data, etc.) are your sole responsibility.</strong></p>
      <h3>2.5 Disabling of an inactive account</h3>
      <p><strong>In order to prevent inefficient resource allocation, if you have not used your Mi Account for 24 consecutive months or have not signed in to your account through other methods approved by Xiaomi, Xiaomi has the right to cancel the account, and you will no longer be able to sign in to the Mi Account or use related services. If there are pending transactions or balances associated with the Mi Account, Xiaomi will provide reasonable assistance in processing them. To this end, you should follow the instructions and notifications provided by Xiaomi.</strong></p>
      <h3>2.6 Account security</h3>
      <p><strong>2.6.1 Your Mi Account is yours to create, set up, and use. Xiaomi will never ask you to provide your password. We recommend that you take specific measures to protect the security of your account, including but not limited to installing anti-virus software and changing your password regularly. </strong></p>
      <p>2.6.2 Xiaomi is not responsible for any losses and consequences caused by your voluntary disclosure of your Mi Account information nor your being defrauded by others. If these circumstances occur, you should seek compensation from the infringer through legal, administrative, or other relevant means. </p>
      <h3>2.7 Canceling an account</h3>
      <p>2.7.1 If you wish to cancel your Mi Account, you may do so by following the steps in Settings &gt; Mi Account &gt; Help &gt; Delete account, or by visiting <a href="https://account.xiaomi.com/">https://account.xiaomi.com</a>. </p>
      <p>2.7.2 Please note that when you cancel your account, Xiaomi will permanently delete all of the data related to that account, except where prohibited by laws and regulations. The Mi Account will also cease to be linked with any third-party accounts.</p>
      <h2>3. User rights and responsibilities</h2>
      <p>3.1 You must abide by the relevant laws and regulations of the People's Republic of China while using Xiaomi services, including but not limited to the Cybersecurity Law, Provisions for the Administration of Internet News Information Services, and Provisions for the Governance of the Online Information Content Ecosystem. You agree that you will not use Mi Account services to engage in any illegal or in appropriate activities, including but not limited to:</p>
      <p>3.1.1 Uploading, displaying, posting, spreading or otherwise transmitting information or content that:</p>
      <ul>
        <li>Violates the basic principles of the constitution;</li>
        <li>Endangers national security, discloses state secrets, subverts state political authority, or threatens national unity;</li>
        <li>Damages national honor and interests;</li>
        <li>Incites racial hatred or discrimination, or harms national unity;</li>
        <li>Violates national religious policy or advocates cults and superstitions;</li>
        <li>Spreads rumors, disrupts social order, or damages social stability;</li>
        <li>Encourages obscenity, pornography, gambling, violence, murder, terrorism, or instigates any crime;</li>
        <li>Insults, slanders, or infringes on the legal rights of other people;</li>
        <li>Contains content that is false, harmful, coercive, harassing, infringing, defamatory, vulgar, obscene, otherwise morally objectionable, or invades the privacy of others; </li>
        <li>Contains other content restricted or prohibited by Chinese laws, regulations, rules, ordinances and any norms with legal effect. </li>
      </ul>
      <p>3.1.2 You shall not use any Xiaomi services to engage in any of the following actions or behaviors:</p>
      <ul>
        <li>Use the resources of or enter computer networks without permission;</li>
        <li>Delete, modify, or add functions of computer networks without permission;</li>
        <li>Delete, modify, or add data and applications that are stored, processed, or transmitted in computer networks without permission;</li>
        <li>Deliberately create or spread computer viruses or other destructive programs;</li>
        <li>Conduct any commercial activities such as publishing advertisements or selling goods, or engage in any illegal acts that infringe upon Xiaomi's interests, such as selling in-game coins, plug-ins, boosters, etc.;</li>
        <li>Undertake any other actions or behaviors that endanger computer network security.</li>
      </ul>
      <p><strong>3.2 You agree to remunerate Xiaomi, its partner companies, and its affiliates for any claim, demand, or loss, including reasonable attorney fees, caused or incurred by any third party against Xiaomi, its partner companies, or its affiliates due to your breach of this Agreement or the relevant terms of service. Xiaomi has the right to take measures including but not limited to deleting published information, suspending licenses, terminating services, restricting the use of the Mi Account, and pursuing legal action, depending on the nature of your actions. Xiaomi will also assist in legal investigations at the request of judicial authorities.</strong></p>
      <p>3.3 You shall not duplicate, reproduce, sell, resell, or otherwise commercially exploit any content contained in our services.</p>
      <p>3.4 You shall bear all legal responsibility for your own actions and behavior while using Xiaomi services. The forms of your legal responsibility include, but are not limited to: a) compensation to any party infringed upon, and b) in the event that Xiaomi first assumes administrative penalty or tort damage caused by your actions, you shall pay Xiaomi an equal amount of compensation.</p>
      <p>3.5 Under no circumstances shall Xiaomi be liable to you or any third party for any indirect, consequential, exemplary, incidental, special or punitive damages arising out of this Agreement.</p>
      <h2>4. Disclaimer</h2>
      <h3>4.1 Xiaomi assumes no legal liability in the event of the following:</h3>
      <p><strong>4.1.1 Provision of your personal information pursuant to legal or government department requirements;</strong></p>
      <p><strong>4.1.2 Any disclosure of personal information due to your misuse;</strong></p>
      <p><strong>4.1.3 Any service disruption, restriction, or other failure to satisfy user requirements due to hacking attacks, computer viruses, blocking of unlawful or harassing information, government controls, or any other reason related to networks, technology, communication lines, or information security administrative measures;</strong></p>
      <p><strong>4.1.4 Any losses or damages to the user caused by third parties due to carrier communication line malfunctions, technical problems, network or computer malfunctions, system instability, or any other reason of force majeure;</strong></p>
      <p><strong>4.1.5 Risks that may arise from using Xiaomi products and services due to threats, defamation, and offensive or unlawful content from anonymous or pseudonymous users;</strong></p>
      <p><strong>4.1.6 Any psychological or physiological injuries or economic losses caused by communication with other users on any Xiaomi platform resulting from misleading or fraudulent behavior;</strong></p>
      <p><strong>4.1.7 Xiaomi expressly states that no express or implied guarantee is provided in any form as to the timeliness, security and accuracy of the services of Xiaomi and its partner companies;</strong></p>
      <p><strong>4.1.8 Any content posted by you using your Mi Account does not represent nor reflect any views or policies of Xiaomi, and Xiaomi does not assume any liability therefor;</strong></p>
      <p><strong>4.1.9 Under no circumstances shall Xiaomi be liable for any indirect, consequential, incidental, special, or punitive damages, including loss of profits suffered by you as a result of your use of Xiaomi services. Even if there exist conflicting provisions in this Agreement, our entire liability to you, no matter the reason or the manner of conduct, will never exceed the fees (if any) you paid to Xiaomi for the use of Xiaomi services during the registration period.</strong></p>
      <p><strong>4.2 You may choose to link your existing third-party account to your Mi Account. In no case will Xiaomi be responsible for any losses caused to you by a third party.</strong></p>
      <h2>5. Intellectual property rights</h2>
      <p>5.1 You agree that in the use of your Mi Account on any platform, you will not infringe upon any rights of any person, including intellectual property rights. You may not upload, post, modify, distribute, or reproduce any copyrighted material, trademarks, or other proprietary information belonging to others without obtaining the prior written consent of the owner of such proprietary rights. After we receive proper notification by the copyright holder or its agent, and confirm through our investigation the validity of the accusation, we will remove any content that infringes upon copyright.</p>
      <p>5.2 You retain any intellectual property rights for the content (including text, images, videos, software, etc.) which you submit, post, or upload on or through our services and/or using Mi Account. By submitting, posting, or uploading the content, you give Xiaomi a perpetual, irrevocable, and non-exclusive license, with a right to sublicense, reproduce, or otherwise use such content.</p>
      <p>5.3 You do not have the right to use any of Xiaomi's intellectual property without Xiaomi's prior written consent. You hereby attest that you respect Xiaomi's intellectual property rights. You shall not apply in any jurisdiction or in any way for a trademark, domain name, website name, logo, trade name, or any other distinctive brand feature that is similar to that of Xiaomi or its affiliates‘ trademarks for any marketing, advertising, promotional or other purposes, whether in your own name or by causing a third party to do so, nor shall you give your consent or allow any third party to do so. If you do so, you shall transfer all relevant rights to Xiaomi at your own expense. You attest that you will not use the following names (including but not limited to "Lei Jun", "Xiaomi", "Mi Link", "Mi Talk", "Mi Store", "mi.com", "Redmi", "Mitu", "MIUI", "Mi Home", or the affiliated logos and images of the above brands) as part of the name of a company, merchant, service, or product, and will not use the Xiaomi trademark or intellectual property similar to the trademark. If you cause any loss to Xiaomi due to your violation of these terms and conditions, you shall bear all such losses.</p>
      <h2>6. Modification of this Agreement</h2>
      <p>You agree that, based on developments in technology, the market, Xiaomi's business model, etc., Xiaomi has the right to amend terms and conditions, including this Agreement, at any time in accordance with changes in Chinese laws and regulations, the development of the internet, and adjustments in company situation and business strategy. We will notify you of the new agreement in an appropriate manner, and you may view the latest version of the terms of the agreement on the relevant service page. <strong>Once the revised agreement and rules are announced, they will take effect immediately and become an integral part of this Agreement. If you do not agree to the modified terms, you shall immediately discontinue your use of our services.</strong> Your continued access or use of our services shall be deemed as your acceptance of the modified agreement.</p>
      <h2>7. Term and termination</h2>
      <p>7.1 This agreement is effective as of the date accepted by you and will remain in effect unless terminated in accordance with the Agreement.</p>
      <p>7.2 Notwithstanding clause 7.1, you will be determined as having accepted this Agreement upon your first use of our services, unless terminated in accordance with the Agreement.</p>
      <p>7.3 We reserve the right in our sole and absolute discretion to suspend or terminate your use of Mi Account and other Xiaomi services at any time without liability or prior notice for any reason, if we believe in good faith that you have violated or acted inconsistently with this Agreement or our Acceptable Use Policy.</p>
      <p>7.4 After proper notification by the copyright holder or its agent and confirmation that the user has used our services as an instrument of unlawful copyright infringement, we will terminate the infringing user's rights to use and/or access to our services.</p>
      <h2>8. Protection of privacy</h2>
      <p>Xiaomi is committed to protecting the privacy of users in accordance with the <a href="https://privacy.mi.com/miaccount/en_US/">Mi Account Privacy Policy</a>. This Agreement and the Privacy Policy constitute the complete agreement between you and Xiaomi regarding Mi Account services. </p>
      <h2>9. Applicable laws and dispute resolution</h2>
      <p><strong>9.1. This Agreement is governed by the laws of the People's Republic of China.</strong></p>
      <p><strong>9.2 If any dispute arises between the two parties, it should be resolved through amicable negotiation. If negotiation fails, a lawsuit should be filed in the Haidian District People's Court in Beijing. If there is a conflict in terms of jurisdiction between any single clause and the terms and conditions of this service, the single clause takes precedence within the scope of its applicability.</strong></p>
      <h2>10. Additional terms</h2>
      <p><strong>10.1 Feedback</strong></p>
      <p>10.1.1 If you provide us any feedback or suggestions regarding our services ("Feedback"), you assign to us all rights to the Feedback and agree that we will have the right to use the Feedback and related information in any manner we deem appropriate. We will treat any Feedback you provide to us as non-confidential and non-proprietary.</p>
      <p>10.1.2 You agree that you will not submit to us any information or ideas that you consider to be confidential or proprietary.</p>
      <p><strong>10.2 Notices</strong></p>
      <p> You agree to provide accurate and current contact information required (including your phone number and email address) to register with Xiaomi for Mi Account services. You further agree to keep such information accurate and current.  <strong>You acknowledge and agree that Xiaomi may send to you, whether by email or otherwise, communications and notifications, which may inform you about changes that impact your rights and responsibilities under this Agreement. It is your responsibility to check these updates periodically. </strong> You understand and acknowledge that failure to provide or update accurate contact information may prevent the notices from reaching you and that you are solely responsible for any losses or damages you suffer as a result of unsuccessful delivery of notices.</p>
      <p><strong>10.3 Severability</strong></p>
      <p>10.3.1 If some provisions of this Agreement cannot be applied for any reason, all other provisions remain valid and are binding on both parties.</p>
      <p><strong>Last updated on February 24, 2022</strong></p>
    </div>
  </div>
</template>

<style scoped >
  @import "style.css";
</style>